!/usr/bin/python3
 -- coding: utf-8 --
# # @Time : 2023/4/4 9:23
# #作者：https://www.52pojie.cn/thread-1231190-1-1.html
# # -------------------------------
 cron "30 4 * * *" script-path=tyyun.py,tag=匹配cron用
 const $ = new Env('天翼云盘签到');
