name: cloundqiandao
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 10 2,14 * * *
    
jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        username='${{ secrets.USER }}'
        password='${{ secrets.PWD }}'
        
        username_list=()
        password_list=()
        IFS=","
        for u in ${username[*]}
        do
        username_list[${#username_list[*]}]=${u}
        done
        for p in ${password[*]}
        do
        password_list[${#password_list[*]}]=${p}
        done
        username_num=${#username_list[*]}
        password_num=${#password_list[*]}
        if [ $username_num != $password_num ];then
        echo "账号和密码个数不对应"
        exit 1
        else
        echo "共有 $username_num 个账号，即将开始签到"
        fi
        for ((i=0;i<$username_num;i++))
        do
        python3 checkin.py --username ${username_list[$i]} --password ${password_list[$i]}
        done
