name: 签到

on:
  schedule:
    - cron: 0 4, * * *
  watch:
    types: started
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3
      - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
          
      - name: 初始化Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
         
      - name: 开始
        run: |
          pip3 install requests
          user='${{ secrets.USER }}'
          passwd='${{ secrets.PWD }}' 
          python3 checkin.py ${user} ${passwd}
