name: 天翼云盘签到抽奖

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 22,14 * * *' 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
            
        
    - name: Checkin
      run: |
        ty_username='${{ secrets.USER }}'
        ty_password='${{ secrets.PWD }}'
        python3 tyyun.py 
        done
